### ISSUE TITLE
Add bullets to milestones

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#101]
turn this into bullets 

<img width="764" alt="Screenshot 2023-08-06 at 09 49 50" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/7115a074-a9a8-42bf-931d-f512f74a7c0e">

**Comment by marcuspang** [comment]
Fixed, had to update prod database
