### ISSUE TITLE
Theres a gap at the bottom and top of the page

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#102]
<img width="1426" alt="Screenshot 2023-08-06 at 09 51 41" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/8fcde7d4-46ee-4a4d-afd6-b2da0774fc8b">

----

<img width="1420" alt="Screenshot 2023-08-06 at 09 52 30" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/9b009e0e-1337-4c44-b774-827728de9620">

**Comment by marcuspang** [comment]
I cant add spacing below the navbar consistently as you scroll down. Since the element is sticky, it's mean to overlap and not affect the body elements as you scroll

**Comment by marcuspang** [comment]
Oh nvm, you want to remove the space
