### ISSUE TITLE
Change name and logo of project creator

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#106]
Change name to be Mochi

Turn logo to be Mochi logo 

<img width="487" alt="Screenshot 2023-08-06 at 20 26 44" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/43fbea3e-1151-4f7c-a590-61ac99fc1ff9">

**Comment by marcuspang** [comment]
Done

**Comment by marcuspang** [comment]
Nvm, for the logo, will need the backend to update the IUser schema

**Comment by marcuspang** [comment]
This is the `profile` field in `IUser` which is an imgur url. Might need an external library to find the video url

**Comment by marcuspang** [comment]
Currently hardcoding the `profile` field for the Mochi project with a GitHub file link, which is not ideal. Need to use the `multipart/form-data` content type to `PATCH /users/:id`

**Comment by marcuspang** [comment]
Will be resolved in admin pages milestone
