### ISSUE TITLE
Change title

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#107]
Change title copy to:

`Mochi’s “But Make It Kawaii” AI Journey Campaign`

<img width="961" alt="Screenshot 2023-08-06 at 20 27 55" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/906723c7-cc9c-4ef6-8ff1-5b963d0afdf8">

**Comment by marcuspang** [comment]
Done
