### ISSUE TITLE
Add tags into the individual project page

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#108]
Add tags here.

I thought this was done though? not sure what happened

<img width="814" alt="Screenshot 2023-08-06 at 21 42 30" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/92d2bcde-dc87-489c-ae3a-c69c3b5632f0">

**Comment by marcuspang** [comment]
The database didn't update properly, is it correct now?

**Comment by RadarDAO** [comment]
Nearly its still wrong here:

￼

**Comment by marcuspang** [comment]
I see it here https://radarlaunch.app/project/64cc1fdaa7c27d4528c2ca00
<img width="615" alt="Screenshot 2023-08-07 at 14 20 58" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/9083891/f2771340-8236-4095-a073-4edacba10e9b">

**Comment by marcuspang** [comment]
Resolved elsewhere
