### ISSUE TITLE
Match padding on project Summary div to benefits div 

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#115]
Make the padding on the left hand column bigger to match the padding on the benefits boxes

<img width="1436" alt="Screenshot 2023-08-07 at 00 16 04" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/6e67bd0b-f0b9-4135-9291-dbeaa20182f9">

**Comment by marcuspang** [comment]
It looks bigger on the right side, because it's smaller. If you inspect element they are about the same. Do you want me to increase the padding more for the left?

**Comment by RadarDAO** [comment]
Yes please, so there’s a visually similar gap. Thanks

**Comment by marcuspang** [comment]
@kevincomp

/project/:id page

Scroll down on left side to see project description

Note that the spacing on the left visually looks smaller than the right, although they are actually thr same pixel padding

Increase the padding on the left to match the right padding visually
