### ISSUE TITLE
Edit project summary section

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#116]
Remove the last bullet and make it a normal sentence, add bullets to

- Image: Diffusion model (e.g. Midjourney)
- Text & Code: Large language model or LLM (e.g. GPT-4)
- Voice: Voice-conversion model (e.g. AI Drake)

<img width="908" alt="Screenshot 2023-08-07 at 00 18 57" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/bdcadd84-d155-430a-b889-fbf149fbcba5">

**Comment by marcuspang** [comment]
Fixed
