### ISSUE TITLE
Change twitter link to mochi on paper payment page

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#117]
https://twitter.com/bondwithmochi

<img width="1378" alt="Screenshot 2023-08-07 at 00 23 45" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/847eee35-dd0f-4a9b-aed5-963d2d5192c1">

**Comment by marcuspang** [comment]
Done
