### ISSUE TITLE
Start the tabs on 'collect' instead of benefits

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#118]
<img width="1436" alt="Screenshot 2023-08-07 at 00 31 54" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/45b19dfa-cadb-482a-be26-151207fbd54b">

**Comment by marcuspang** [comment]
Here, just change this default value to the collect one

https://github.com/RadarDAO-xyz/radar-launch-frontend/blob/b3b8f4a39d3ef0051685cdf95693b0128a5d312a/components/ProjectTabs.tsx#L226
