### ISSUE TITLE
Update share update and edit profile to link to the correct page

### ISSUE THREAD

**Issue by marcuspang** [RadarDAO-xyz/radar-launch-frontend#120]
<img width="1322" alt="Screenshot 2023-08-07 at 01 21 27" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/9083891/237c2c32-9db2-455a-9ba7-2fb2f41433a9">

Will require changes to the endpoints for "share update" and "edit profile" (i.e. `/update-profile` and `/updates`), best to have it under `admin/:id/edit` and `admin/:id/updates`

**Comment by kevincompton** [comment]
@marcuspang this is outdated with most recent changes
