### ISSUE TITLE
Final changes

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#123]
Change these tags to be 'Coordination' 'Crypto ' Ai'

<img width="874" alt="Screenshot 2023-08-07 at 17 08 51" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/04747dc4-b5fe-448c-aeb0-2b4a47c44416">

**Comment by RadarDAO** [comment]
This copy is still wrong it needs to read

And with consent. we then used the datasets to train 4 community-specific intelligences:

- Image: Diffusion model (e.g. Midjourney)
- Text & Code: Large language model or LLM (e.g. GPT-4)
- Voice: Voice-conversion model (e.g. AI Drake)


<img width="856" alt="Screenshot 2023-08-07 at 17 10 07" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/a4541e90-fb81-4018-a369-ef95baf6f94c">

**Comment by RadarDAO** [comment]
This needs to be updated to show drop #2 as 2nd and then add back in the drop details

<img width="1382" alt="Screenshot 2023-08-07 at 17 11 51" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/473cd8af-a599-4784-8483-f984aa318b74">

**Comment by RadarDAO** [comment]
this needs to be changed to 15 days


<img width="429" alt="Screenshot 2023-08-07 at 17 13 34" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/e1ca7a3e-c98b-4376-98ad-1342c4f84299">

**Comment by RadarDAO** [comment]
Change this microgramma copy 'Inter' and also in the contributors title too

<img width="889" alt="Screenshot 2023-08-07 at 17 14 20" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/1207530d-b2e5-42d6-a3af-e7ed3e813882">
<img width="458" alt="Screenshot 2023-08-07 at 17 14 18" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/6fa42f98-aba6-44a1-bab4-dadaf4264c94">

**Comment by RadarDAO** [comment]
Decrease `leading` on microgramma on the project so titles match

<img width="1139" alt="Screenshot 2023-08-07 at 17 19 26" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/8f19c3ed-2dc0-4e03-b89d-b5aca3890568">

**Comment by marcuspang** [comment]
> And with consent. we then used the datasets to train 4 community-specific intelligences:
> 
> - Image: Diffusion model (e.g. Midjourney)
> - Text & Code: Large language model or LLM (e.g. GPT-4)
> - Voice: Voice-conversion model (e.g. AI Drake)

Not sure how it's supposed to be, but I just updated it

**Comment by RadarDAO** [comment]
> > And with consent. we then used the datasets to train 4 community-specific intelligences:
> > 
> > * Image: Diffusion model (e.g. Midjourney)
> > * Text & Code: Large language model or LLM (e.g. GPT-4)
> > * Voice: Voice-conversion model (e.g. AI Drake)
> 
> Not sure how it's supposed to be, but I just updated it

Yeah so close this text just needs to be in bullets

<img width="420" alt="Screenshot 2023-08-07 at 17 31 13" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/026e2827-d07d-4868-a63f-35b12ef8a521">

**Comment by RadarDAO** [comment]
Change to all caps

<img width="362" alt="Screenshot 2023-08-07 at 17 41 36" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/416540ee-7485-4d4c-a7d6-545513cde447">

**Comment by RadarDAO** [comment]
Update these to have the final supporter + countdown stat data!

<img width="327" alt="Screenshot 2023-08-07 at 17 46 10" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/c7653598-3072-4290-acdc-2fb967e81a38">

<img width="627" alt="Screenshot 2023-08-07 at 17 46 18" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/72e34895-89a3-494a-b736-6ab76b1f281c">

See here:

<img width="664" alt="Screenshot 2023-08-07 at 17 47 50" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/9b9037ed-e339-4df5-84b3-505775fcdcdb">

<img width="322" alt="Screenshot 2023-08-07 at 17 49 06" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/9c764d9d-747d-41a6-b92c-82689027bc76">

**Comment by RadarDAO** [comment]
remove the 0xBc... link

add the word contract at the bottom of the div and link to the contract so people can check it if they want

<img width="456" alt="Screenshot 2023-08-07 at 17 57 13" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/fc881b1d-30a0-497a-8830-df3df61bc359">

**Comment by marcuspang** [comment]
> Make all the drop dates align at the bottom
> 
> <img alt="Screenshot 2023-08-07 at 17 16 42" width="1412" src="https://user-images.githubusercontent.com/103267267/258847259-fcd5871b-0240-4f08-8dad-c4375aed9e5e.png">

TODO

**Comment by marcuspang** [comment]
> update twitter link to be https://twitter.com/messages/1171212388541972480-1384880041407000579 instead of RADAR and say 'Mochi'
> 
> <img alt="Screenshot 2023-08-07 at 17 21 58" width="1153" src="https://user-images.githubusercontent.com/103267267/258848365-989ef836-c6ec-4643-a49d-dd578cad348e.png">

Not sure if possible, TODO

**Comment by marcuspang** [comment]
@RadarDAO do you think we can have the twitter link be the socials

**Comment by RadarDAO** [comment]
yeah, 100% just link to their twitter https://twitter.com/bondwithmochi

**Comment by RadarDAO** [comment]
oh or our socials if you can't change it https://twitter.com/Radarxyz

Not a priority for me as theres other stuff i'd rather we did

**Comment by marcuspang** [comment]
Rest have been resolved
