### ISSUE TITLE
Milestone content wrong, I thought we sorted this. WEIRD.

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#125]
<img width="882" alt="Screenshot 2023-08-07 at 19 00 29" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/fb834134-4ac7-4a3b-bf0b-bda44db56a7f">

^^ this is wrong. It needs to be See below

**Comment by RadarDAO** [comment]
Milestone 2:

Tune our Kawaii AI with 10,000 community-curated submissions.

- SPAWN: 10,000 image samples
- WRITE: 10,000 text completions
- CODE: 10,000 code completions
- SPEAK: 100 hours of recorded voice samples

**Comment by RadarDAO** [comment]
Milestone 3:

Release our Kawaii AI framework publicly so any community can grow and sustain their own CSI with its unique dataset according to its needs.

**Comment by RadarDAO** [comment]
Milestone 4:

Integrate Kawaii AI into @mochibot

**Comment by marcuspang** [comment]
Resolved
