### ISSUE TITLE
Not loading on optimism 

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#130]
<img width="624" alt="Screenshot 2023-08-08 at 00 39 32" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/c5007ae7-1345-415c-8f2f-8ab90dcb6ca1">

**Comment by marcuspang** [comment]
I have raised it with the thirdweb support but they are not really helping

**Comment by marcuspang** [comment]
See https://discord.com/channels/834227967404146718/1136695062772842588

**Comment by marcuspang** [comment]
@RadarDAO do you think we could add another button temporary to pay on optimism?

**Comment by RadarDAO** [comment]
Where would it be placed?

**Comment by RadarDAO** [comment]
Yeah that would be epic, as long as its a nice pop-up

Could it be

‘Collect with Card'
'Collect with Optimism’

And then maybe we remove all the web3 options from paper.

How about that as a solution?

Then its super clear choice?

**Comment by marcuspang** [comment]
I think it's still good to have a way to pay on ETH mainnet, what do you think?

**Comment by RadarDAO** [comment]
Yeah ok, lets just remove optimism from that pkperwallet option and also make it clear paper means card or ETH

Cause a lot of people won’t know what paper is

**Comment by marcuspang** [comment]
Will be fixed here https://github.com/RadarDAO-xyz/radar-launch-frontend/issues/130
