### ISSUE TITLE
Can we change this word to 'Supporters' and + sign ups + collaborators form

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#133]
Can we adjust this number to include

```
# of NFTs collected
# of people signed up
# of people signed up to be a collaborator
```

<img width="422" alt="Screenshot 2023-08-08 at 09 15 31" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/a522f458-d6af-4248-b7ca-525b4304d7ff">

**Comment by marcuspang** [comment]
How would that look like? Like this?

countdown . # collected
# sign ups  .  # collaborators

**Comment by RadarDAO** [comment]
No its still just 1 number

# supporters

But supporters is made up of

Collections + Sign ups + collaborators

Does that make sense?

**Comment by RadarDAO** [comment]
And this applies to everywhere you see #collectors currently
