### ISSUE TITLE
RADAR Launching NFT collections on the 9th needs no max limit on edition price

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#134]
On the 9th. RADAR is creating 4 separate pages where you collect NFTs on each to fund its research.

We will need to submit via the form. @marcuspang can you remove the edition price max limit for this. as we're charging more.

These do not need to be featured on the site.

They're linked from a separate page - https://www.radardao.xyz/patron-live

**Comment by marcuspang** [comment]
Okay I will set the max price to something like 10,000 usd

**Comment by RadarDAO** [comment]
Perfect, exactly cause the top tier is 10k!

Its a joke but imagine if we sold one haha

**Comment by marcuspang** [comment]
Oh damn, maybe I should have increased it higher

**Comment by marcuspang** [comment]
Updated to 50eth

**Comment by RadarDAO** [comment]
For these projects, Am I able to create them yet? We could create them with placeholder images and then update the metadata of the image tomorrow. Just to make sure theres no errors / blockers.

They're going to be videos as the NFTs, can we make that happen?
