### ISSUE TITLE
Update this to be ~$10 and ~$1

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#139]
Lets round to $10 and get rid of the decimals as it looks a little confusing 

<img width="402" alt="Screenshot 2023-08-08 at 16 46 19" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/8bafe7bb-1739-4c3b-a794-264a31b10ee7">

**Comment by marcuspang** [comment]
This is /project/:id page

Go to collect tab on right side

Note that the numbers have a lot of decimals

Please round it off
