### ISSUE TITLE
Make project blocks all clickable 

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#140]
After this comment its

1. Add a big button
2. Make the whole project div clickable and show click cursor

wdyt?

<img width="394" alt="Screenshot 2023-08-08 at 17 55 30" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/1f979006-b589-4e61-b282-f8da6c27461f">

**Comment by marcuspang** [comment]
@RadarDAO still valid?

**Comment by RadarDAO** [comment]
No solved with the arrows I think
