### ISSUE TITLE
Show Metadata preview 

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#141]
Lets take this from the project submission

Radar Launch - [project name]

[project description]

<img width="371" alt="Screenshot 2023-08-08 at 17 56 26" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/391666aa-4b30-445e-a224-f7ebdf79f2a4">

**Comment by marcuspang** [comment]
I believe this is related to the <meta /> tags inside Next.js <Head />, namely og:title, and the twitter ones
