### ISSUE TITLE
Update countdown drops and dates as we've now moved launch days

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#150]
<img width="1020" alt="Screenshot 2023-08-09 at 21 18 49" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/04bf5e6b-a921-4155-944c-255c6d8382d9">

Drop #2 8pm UK Monday 14th August
Drop #3 8pm UK Monday 21st August
Drop #4 8pm UK Monday 28th August

**Comment by marcuspang** [comment]
Updated
