### ISSUE TITLE
Add $ sign to these numbers 

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#154]
<img width="404" alt="Screenshot 2023-08-09 at 22 56 04" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/3e53f990-7b6a-4653-9c09-70568294927f">

**Comment by kevincompton** [comment]
I don't understand this ticket, you needed my help to add 2 $ to a file? Not the best use of my time.
