### ISSUE TITLE
ADD NFT METADATA IMAGES FOR NFT PROJECT

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#156]
edition 2
Advocates

https://bafybeieumcu4wj7wg53klru6i36qfaa4lqbg63p3fln46g5wnraxyfz7nm.ipfs.nftstorage.link/ 

Edition 3
Angels 

https://bafybeiaklxd7joocsdym6n6srzvviekrcg5vr6v34tki5cdgvxeyjxfdz4.ipfs.nftstorage.link/

Edition 4
Sponsors

https://bafybeifg2dogndbtuyrvdxcmxdlbbqbqh4pqoyagjk7xsxpxqojkfl6xiu.ipfs.nftstorage.link/ 

Edition 5
Supporters

https://bafybeiafbjufam6cq774cjli2rypci7fcxapvbeqwdx3ruppxdg6ioltfq.ipfs.nftstorage.link/

**Comment by marcuspang** [comment]
Added
