### ISSUE TITLE
Remove numbers of team members

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#157]
can we remove numbers when we list the team of projects on all individual project pages

<img width="237" alt="Screenshot 2023-08-10 at 00 04 17" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/ebad0af3-c8af-4881-a596-6b02d9c04e88">

**Comment by marcuspang** [comment]
Number here refers to list index numbers 

Please hide them using css with list style none
