### ISSUE TITLE
Switch Youtube links for vimeo links and remove all HUD except for playbar

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#158]
<img width="456" alt="Screenshot 2023-08-10 at 00 37 58" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/5e22ce3f-ea59-4c56-bd31-f794f914f376">

Angels 

https://vimeo.com/853179512?share=copy 

Advocates

https://vimeo.com/853179380?share=copy 

Supporters

https://vimeo.com/853179603?share=copy 

Sponsors

https://vimeo.com/853179246?share=copy

**Comment by marcuspang** [comment]
Updated
