### ISSUE TITLE
Is the number of supporters showing right?

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#159]
This is showing 54 for mochi, but it might actually be 52 and 2 of the other NFTs, just wanna make sure we're gettign these numbers right, and each project is only showing its own count of sales + sign ups + contributors

<img width="708" alt="Screenshot 2023-08-10 at 09 41 07" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/ba70f9ed-54c7-4868-90ff-d93e86324c59">

<img width="616" alt="Screenshot 2023-08-10 at 09 40 31" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/1a935da2-f2b9-4aa5-a78d-b90591968ec1">

**Comment by marcuspang** [comment]
Remember you said it includes the number of sign ups and contributors?

**Comment by RadarDAO** [comment]
Yeah, so we've only had 2 people sign up or agree to contribute? I signed up with like 4 different emails! If we could take a look at this I'd appreciate it!
