### ISSUE TITLE
These arrow links shouldn't click out to real projects, disable click

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#160]
<img width="1014" alt="Screenshot 2023-08-10 at 12 18 57" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/46e08326-2039-4d6d-a408-3b9679485e01">
<img width="1343" alt="Screenshot 2023-08-10 at 12 19 50" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/27f6309d-9f6f-451d-9881-f9973bbd0ec0">

**Comment by marcuspang** [comment]
Here the arrow refers to the arrow pointing up-right diagonally in the project block for the first image.

We want to disable it if the project status is not LIVE, i.e. pass `disabled` as `true` (based on project status), to `<Link />`. If it's a button disabled it too
