### ISSUE TITLE
Update this link on individual /project page to click through to /profile page

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#195]
<img width="476" alt="Screenshot 2023-08-11 at 13 40 19" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/ee2df88d-a250-4901-b78b-b061584fd2f4">

goes to demo: https://www.launch.radardao.xyz/founder-profile

**Comment by marcuspang** [comment]
You mean the founder profile page? Done
