### ISSUE TITLE
Pool Page Issue

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#20]
Title Section

1. Add sign up form (make text black) and send email to airtable
2. Add 5% padding on top and bottom

---
<img width="853" alt="Screenshot 2023-07-29 at 17 40 25" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/a0838c97-5a84-4e4d-b1ea-70a989ccbe84">

**Comment by RadarDAO** [comment]
Add padding to the tab content, 50px?

<img width="1170" alt="Screenshot 2023-07-29 at 17 25 44" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/ad908df5-933f-4de3-acdb-955d2e7583c6">

**Comment by RadarDAO** [comment]
1. Add 20px gap under copy
2. Turn copy to MICROGRAMMA CAPITALS

<img width="1071" alt="Screenshot 2023-07-29 at 17 27 19" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/6e208e52-611a-44d7-9dd8-e136baa10b36">

**Comment by RadarDAO** [comment]
<img width="173" alt="Screenshot 2023-07-29 at 17 28 07" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/58b4cc97-b80a-4a04-8caa-3112ebfd4b48">
add this link to `'learn more about pools'`

https://radarxyz.notion.site/Funding-Pools-Partner-Briefs-07b0753b0f6f401f9249fe8e0537ef03?pvs=4

**Comment by RadarDAO** [comment]
Add Funding pool holder component 
- add countdown clock till brief is live

<img width="1242" alt="Screenshot 2023-07-29 at 17 31 01" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/7ef49c94-aee8-4ace-be42-2925017d5336">

**Comment by marcuspang** [comment]
> <img alt="Screenshot 2023-07-29 at 17 28 07" width="173" src="https://user-images.githubusercontent.com/103267267/256990906-58b4cc97-b80a-4a04-8caa-3112ebfd4b48.png"> add this link to `'learn more about pools'`
> https://radarxyz.notion.site/Funding-Pools-Partner-Briefs-07b0753b0f6f401f9249fe8e0537ef03?pvs=4

Do you mean the button should be microgamma?
