### ISSUE TITLE
Create Funding Pool page for Kernel x Buidl Guidl

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#239]
Using mockup here:

https://launch-testing-56809a-a28-18cf5d11f6289.webflow.io/kernel-funding-pool

**Comment by marcuspang** [comment]
@RadarDAO do you have the link to buidl guidl logo image? 

Currently the pool is here https://radarlaunch.app/pool/64ee74a442d2582b74e47f83

**Comment by marcuspang** [comment]
Buttons are awaiting schema update in backend
