### ISSUE TITLE
Update Profile Page

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#24]
Remove `Edit profile`
Remove `Projects`

<img width="1096" alt="Screenshot 2023-07-29 at 18 31 47" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/6ceee2fe-a718-4c0a-8cd5-0bb7d1998f2d">

**Comment by RadarDAO** [comment]
When this page is filled out, it holders the information in it, becoming the profile, and then can be updated from this page.

<img width="1116" alt="Screenshot 2023-07-29 at 18 39 04" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/aa7faee1-12d0-4cb4-bab6-7dbc868a9931">

Expand text box and make it rich text to add links etc

**Comment by RadarDAO** [comment]
<img width="304" alt="Screenshot 2023-07-29 at 18 39 32" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/28e320c0-c68e-41ac-b47d-645aaba12c8b">

Show image when uploaded

**Comment by kevincompton** [comment]
@marcuspang all of the above was updated except for the image upload and also this form needs to update the user and the admin nav needs real data

**Comment by marcuspang** [comment]
@kevincompton yes, that's why the issue is still open

**Comment by marcuspang** [comment]
Rest have been resolved
