### ISSUE TITLE
Edit the 'Curated Visions' section on the home page and move 'august curated by Culture3' to underneath the projects, rather than header

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#241]
Change 'Curated visions' to 'Curated by Culture3'

<img width="1438" alt="Screenshot 2023-08-28 at 21 42 37" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/84634cfb-6968-49b4-b0bd-98ec5798ec89">

"Culture3 spotlights 4 projects building a better future"

**Comment by marcuspang** [comment]
Is the button text changed from "get drop updates"? Or is it just the link is changed @RadarDAO

**Comment by RadarDAO** [comment]
ah yes, sorry @marcuspang lets just remove that button entirely tbh. We might use it again so many just hide for now

**Comment by marcuspang** [comment]
So should I still add the "curated by culture3" at the bottom right here? @RadarDAO

**Comment by RadarDAO** [comment]
yes lets move the logo it from the header section and down here
