### ISSUE TITLE
send email to admin@radardao.xyz when new project submits

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#243]
just need a notification that a new project has submitted so I can get on it!

Can that email also contain:

1. link to project
2. Email of submitter (project team member #1)

**Comment by marcuspang** [comment]
@mrTomatolegit could you add this email for @RadarDAO?

**Comment by RadarDAO** [comment]
oh yeah that would be cool @mrTomatolegit

**Comment by mrTomatolegit** [comment]
Doing all emails then
