### ISSUE TITLE
Replace the 'your name' with '0x...adress'

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#245]
<img width="557" alt="Screenshot 2023-08-28 at 22 24 44" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/a0450b4e-8a80-48af-8acf-066b8971112e">

**Comment by marcuspang** [comment]
I believe this should be the first team member details, instead of the address
