### ISSUE TITLE
When project is shared on socials etc - it takes the share metadata of the project

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#249]
Image NFT = image
Metadate Title = title project

Just to update this so its promoting the project vs launch
<img width="473" alt="Screenshot 2023-08-29 at 10 24 04" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/0665ec32-e0f3-438b-8f89-1509b735a4e5">

**Comment by thisisommore** [comment]
This is unexpected since the og meta tags are already there.
I suspect NextSeo is not working properly, we can use https://nextjs.org/docs/app/api-reference/functions/generate-metadata#generatemetadata-function instead.
https://github.com/RadarDAO-xyz/radar-launch-frontend/blob/619914d2d2b37e5f01efea67500ec12173d383ee/pages/project/%5Bid%5D/index.tsx#L65-L71

**Comment by marcuspang-cliniserve** [comment]
> This is unexpected since the og meta tags are already there.
> 
> https://github.com/RadarDAO-xyz/radar-launch-frontend/blob/619914d2d2b37e5f01efea67500ec12173d383ee/pages/project/%5Bid%5D/index.tsx#L65-L71
> 
> I suspect NextSeo is not working properly, we can use [NextJS/generateMetadata](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#generatemetadata-function) instead.

Yes, which was why I wanted to make these pages load server side initially. But I had quite a few errors with vercel when doing it for the homepage / project page, so I held it off first.

**Comment by marcuspang** [comment]
> This is unexpected since the og meta tags are already there.
> 
> https://github.com/RadarDAO-xyz/radar-launch-frontend/blob/619914d2d2b37e5f01efea67500ec12173d383ee/pages/project/%5Bid%5D/index.tsx#L65-L71
> 
> I suspect NextSeo is not working properly, we can use [NextJS/generateMetadata](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#generatemetadata-function) instead.

Yes, which was why I wanted to make these pages load server side initially. But I had quite a few errors with vercel when doing it for the homepage / project page, so I held it off first.

**Comment by thisisommore** [comment]
@marcuspang I will try to fix this issue, can you tell me which env keys are required to set for that page, or it is required to set all envs?
