### ISSUE TITLE
Linking out to webflow pages

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#26]
In the nav bar: we have a bunch of pages we don't want to build in react

E.g 

How it works, Why, etc.

We'll keep these pages in webflow and then connect them after

<img width="782" alt="Screenshot 2023-07-29 at 18 54 23" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/97c823d1-324d-404c-8c94-8dcf73c46089">

**Comment by kevincompton** [comment]
@RadarDAO what are the url's?
