### ISSUE TITLE
MAJOR UX update to believe & Collect on project page

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#263]
To declutter the page and make sure the the major focus (which is believe + collect) lets move everything else in that grid to other parts of the page.

The biggest change here is 'collect' is optional. If projects do not turn on 'collect' then users will not be able to collect the NFT however it will still be created by the project creator #268 

https://launch-testing-56809a-a28-18cf5d11f6289.webflow.io/project-copy 
<img width="1429" alt="Screenshot 2023-09-07 at 16 41 05" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/b66b32f8-ab7b-4a11-bf5f-7f04f43bfb84">

Move benefits into the main part of the copy. Just Before milestones. If empty just list the default.

<img width="1437" alt="Screenshot 2023-09-07 at 16 41 43" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/8d62d289-98c5-4e99-b8c0-fc6cbcb989ff">

Move sign up and contribute to the page tabs and replace contribute which we're not using.

<img width="930" alt="Screenshot 2023-09-07 at 16 41 12" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/bd717cc8-6eac-43c4-8931-0ce777d74fde">

**Comment by marcuspang** [comment]
The collect checkbox is currently hidden, so the tab being hidden will be implemented once that's available
