### ISSUE TITLE
MAJOR UX update on homepage

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#265]
https://www.loom.com/share/a6ce1643000f4d7c99850a8cfc243c53?sid=db7cdea7-85cf-4fbc-a8dd-6aa7db268399

<img width="686" alt="Screenshot 2023-09-11 at 17 39 50" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/142eb908-1b6b-4c36-a312-362667e113b8">

1. Add tags from the project under the video
2. Add a believe button (in the future this will also show the amount of believers) and grey on hover
3. `Read more` links to project page
4. Square all the corners

**Comment by RadarDAO** [comment]
<img width="1345" alt="Screenshot 2023-09-11 at 17 41 49" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/8206d3e7-99cf-4b0c-9324-b568c9f2d19b">

1. Square edges
2. Add believe button
3. Add tags under title

**Comment by RadarDAO** [comment]
When you click believe see popup

<img width="1438" alt="Screenshot 2023-09-11 at 17 44 15" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/e3c85533-194d-4c21-aebe-e34f53229e92">

1. Blur background
2. Pull in title & description
3. Add buttons
4. Show other believers

**Comment by marcuspang** [comment]
What does "read more" do?

**Comment by RadarDAO** [comment]
takes you to project page
