### ISSUE TITLE
UX adjustments on home page popups

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#269]
<img width="1032" alt="Screenshot 2023-09-16 at 14 23 10" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/d03918a3-0b66-454a-89a8-e72715c76bf8">

1. Add bigger margins around the edges + make title UPPERCASE
2. Change read more to grey button
3. Don't let background scroll (sorry if thats shows via the video, thats just my ability on webflow) 
4. Make tags smaller

**Comment by marcuspang** [comment]
3. then you cant see tags at all
