### ISSUE TITLE
Adding futures tags to Launch

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#63]
Got an additional request to make for the project page and submission page.

I want to add a form field in the project submission form where a project can 'tag' the project.

E.g Ai, Crypto, Coordination

Then that appears underneath the one liner description on the project page.

This becomes an important part of the user collecting the project.

They're building reputation in these tags which the future maker has set in the submission.

In the future I want these tags to appear on every users profile page.

**Comment by RadarDAO** [comment]
this is how they look the project page
<img width="651" alt="Screenshot 2023-08-02 at 12 30 28" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/34aaf8d2-d9a3-4c55-8a80-adb61b05119f">


The project will auomatically get 'A More Playfull future' because thats the overall topic + tags they give it

**Comment by RadarDAO** [comment]
For the submission form

![Uploading Screenshot 2023-08-02 at 12.33.53.png…]()

**Comment by marcuspang** [comment]
@RadarDAO  Is this field mandatory?
