### ISSUE TITLE
Individual Project Page

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#84]
This page

<img width="1383" alt="Screenshot 2023-08-04 at 00 17 35" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/3db00a1e-2e6a-457c-bf5b-339e15aa236c">

**Comment by RadarDAO** [comment]
Only show first few characters of the string.

Link out the address to the etherscan view 

<img width="392" alt="Screenshot 2023-08-04 at 00 19 29" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/40418d70-78cb-4505-97e0-baf8d857e33e">

**Comment by RadarDAO** [comment]
Remove outer wrapper box on individual benefits divs

<img width="477" alt="Screenshot 2023-08-04 at 00 21 11" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/ed8a0390-8439-4868-9be5-b9ad9edc14aa">

**Comment by RadarDAO** [comment]
Increase bottom margin on sign up and collaborate

Change title to CAPS CASE

<img width="445" alt="Screenshot 2023-08-04 at 00 21 49" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/7ff8e300-7cc4-4022-8e7d-5344e7e3657c">

**Comment by RadarDAO** [comment]
1. Increase inside padding on display
2. Move tabs in
3. Round edges of box to match other divs


<img width="861" alt="Screenshot 2023-08-04 at 00 24 03" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/76e1747d-8bf6-4172-a782-d7e21978f069">

**Comment by RadarDAO** [comment]
Make the brief & Subtitle grey instead of black 

<img width="361" alt="Screenshot 2023-08-04 at 00 26 15" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/da1eb075-14bd-4fd8-8cee-8b5c1fbe26db">

**Comment by RadarDAO** [comment]
Top align funding milestone numbers*

<img width="799" alt="Screenshot 2023-08-04 at 00 27 55" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/1a2f31a2-224c-4736-9fb3-6e4f4fff34b4">

**Comment by RadarDAO** [comment]
Change the word 'vision' to 'project' in sign up and collaborate

<img width="420" alt="Screenshot 2023-08-04 at 00 30 19" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/77826a96-731c-4c37-8560-c1b4f4566dce">

**Comment by RadarDAO** [comment]
Add a coming soon filler message for empty updates box

<img width="873" alt="Screenshot 2023-08-04 at 00 30 57" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/26e752a2-d960-4a64-a554-693af18d68c5">

**Comment by RadarDAO** [comment]
1. Show price of ETH in $ so web2 people get it
2. how protocol fee + project cost so its not a shock when people collect
3. Centre number in counter box

<img width="473" alt="Screenshot 2023-08-04 at 00 33 54" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/c71b1444-ca8e-4b62-9a1e-dde6c44a0657">

<img width="445" alt="Screenshot 2023-08-04 at 00 32 57" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/65b30ab5-17e4-4c9e-86c5-a0f7ce5c7a13">

**Comment by RadarDAO** [comment]
Add 10vh under the last benefit so its easier to scroll to the bottom without the page jerking

<img width="596" alt="Screenshot 2023-08-04 at 00 48 36" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/896ccb78-1186-482c-b387-783515e9967d">

**Comment by RadarDAO** [comment]
Mobile Layout stacked, with floating button called 'support' which opens into menu


https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/e2bd8ff2-df9c-476b-9eaf-7f0c558f0049



![IMG_1928](https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/d8be5784-732b-44fd-b38a-a449d3d7232f)

**Comment by RadarDAO** [comment]
add 10px spacing between paragraphs

<img width="950" alt="Screenshot 2023-08-04 at 01 01 52" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/24443eed-e84e-48bb-bd45-1fbb9e9e006e">

**Comment by RadarDAO** [comment]
Add bullets to benefits

<img width="442" alt="Screenshot 2023-08-04 at 01 02 43" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/0f8ab2bd-e875-40a6-b9d4-155dc340c2f2">

**Comment by RadarDAO** [comment]
Add the futures tags

<img width="917" alt="Screenshot 2023-08-04 at 10 04 27" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/75936738-0e1b-4160-b9b5-fc569c04ee37">

**Comment by marcuspang** [comment]
> `Coordination` `Crypto` `Ai`

How do we know which tag is dark or light

**Comment by RadarDAO** [comment]
Make 'A More Play-Full Future' dark and the others light

**Comment by marcuspang** [comment]
> Sorry, add 'A More Play-Full Future' as dark and the others light

Sorry I was referring to how we decide which one is dark / light in the backend

**Comment by RadarDAO** [comment]
@marcuspang 

All the projects will recieve a dark 'A More Play-Full Future' by default

And then there should be a new field in the form in the application where you can add tags @mrTomatolegit I think added it?

**Comment by marcuspang** [comment]
> Mobile Layout stacked, with floating button called 'support' which opens into menu
> 
>  RPReplay_Final1691103234.mp4 
> ![IMG_1928](https://user-images.githubusercontent.com/103267267/258253849-d8be5784-732b-44fd-b38a-a449d3d7232f.PNG)

Left with displaying the support bottom at the bottom to display action buttons (collect, sign up, contribute, ...)

**Comment by RadarDAO** [comment]
1. Make founder name bigger than 0x.
2. Turn 0x to lighter grey

Current

<img width="270" alt="Screenshot 2023-08-05 at 15 52 47" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/1fba4e45-c079-42bb-8f8f-9644c205f031">

Result

<img width="310" alt="Screenshot 2023-08-05 at 15 53 05" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/e7919f9a-0fb8-44c0-876b-6014dcdd537a">

**Comment by RadarDAO** [comment]
Turn text to grey, and number to black

<img width="192" alt="Screenshot 2023-08-05 at 15 53 49" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/2d4d0843-d548-4284-ae01-493e5009b2cd">

**Comment by RadarDAO** [comment]
Make the brief and the byline smaller.

Current

<img width="507" alt="Screenshot 2023-08-05 at 15 54 47" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/116aba6a-2e74-49ab-87f2-e845b44158fa">


Goal

<img width="366" alt="Screenshot 2023-08-05 at 15 54 23" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/bfc29820-6f98-44ce-b118-27d71d829dec">

**Comment by RadarDAO** [comment]
- Decrease the vertical padding
- Increate the width padding
- Add bullets to benefits 

<img width="446" alt="Screenshot 2023-08-05 at 15 55 40" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/15325672-0fd8-413b-aa58-b67838b9b4f1">

**Comment by RadarDAO** [comment]
Line up video with edge of text

<img width="907" alt="Screenshot 2023-08-05 at 15 58 13" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/ec43f139-b111-487c-81af-555bda9a2223">

**Comment by RadarDAO** [comment]
Add more padding around collect div

Add a $ sign before `number` USD

Current

<img width="431" alt="Screenshot 2023-08-05 at 16 01 22" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/127bfe78-b100-430d-beba-9d6b5e28c91e">

Goal

<img width="470" alt="Screenshot 2023-08-05 at 16 00 12" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/b90cb0c5-8f57-430f-b6a5-44af16e61506">
