### ISSUE TITLE
Add this logo to Mochi project image 

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#85]
![Logo Fill Stroked@2x](https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/446adbca-68c3-42ad-8ee4-a1d44358f2a7)

**Comment by marcuspang** [comment]
@RadarDAO do you have a hyperlink to where this image is hosted? If not I'm going to use this github link

Also, where will this image show up? I imagine this is used for the mint checkout page

**Comment by marcuspang** [comment]
Used github image
