### ISSUE TITLE
Change the $500 milestone numbers to a -

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#87]
Lets actually remove the $500 and switch it for an empty symbol

For example 

`-`

<img width="253" alt="Screenshot 2023-08-04 at 12 28 13" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/0dcd1422-c524-4fe5-814a-7fe45fcecbb8">

**Comment by marcuspang** [comment]
@kevincompton I've addressed it in the related PR
