### ISSUE TITLE
Mint issues

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#89]
1. Replace the image with the thumbnail from the project, thats the nft
2. Change the title to name of the project
3. Update copy to say Your purchase will be transferred to this wallet....' Select Email if you do not want to pay with crypto'
`
<img width="1385" alt="Screenshot 2023-08-04 at 13 28 18" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/adaf720c-c71c-4ca4-9624-22b0914adb09">

**Comment by RadarDAO** [comment]
Can we change the typeface to be a sans serif throughout paper?
<img width="1385" alt="Screenshot 2023-08-04 at 13 28 18" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/5334c945-51bc-4164-9792-59ac0dfb0e9b">

**Comment by RadarDAO** [comment]
Wrong price when selecting 2 NFTs

<img width="1172" alt="Screenshot 2023-08-04 at 13 33 30" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/494bf7a6-dd0b-4c9f-b31b-a7a212282c0b">

**Comment by RadarDAO** [comment]
You receive this email when you sign up

Can we change this to RADAR Launch 

<img width="531" alt="Screenshot 2023-08-04 at 13 38 02" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/a19add12-b7ef-4511-b7be-ea274a2e3211">

**Comment by RadarDAO** [comment]
Why does it let you choose pay with ETH or Optimism?

Which chain will the NFT be deployed too? Always optimism but you can pay with bot. Super interesting

**Comment by RadarDAO** [comment]
NFT edition is showing no project metadata and is created with your name in, just a heads up

<img width="1406" alt="Screenshot 2023-08-04 at 13 49 15" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/158e33bb-ebb5-4271-a9b7-1b6d4538c8c5">
<img width="922" alt="Screenshot 2023-08-04 at 13 49 21" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/7b5f97bd-b277-4ee3-8a63-78b668ed77d2">
<img width="259" alt="Screenshot 2023-08-04 at 13 51 35" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/2033870f-63a4-40c7-85a2-c159f5bec763">

**Comment by marcuspang** [comment]
> Can we change the typeface to be a sans serif throughout paper? <img alt="Screenshot 2023-08-04 at 13 28 18" width="1385" src="https://user-images.githubusercontent.com/103267267/258408165-5334c945-51bc-4164-9792-59ac0dfb0e9b.png">

Your font family is not loading for some reason, it has a different font for me

**Comment by RadarDAO** [comment]
Show $ equivalents here instead of ETH

<img width="379" alt="Screenshot 2023-08-04 at 15 10 48" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/41d114f5-1547-4318-8e6f-517c1d8ab5c2">

**Comment by marcuspang** [comment]
Issues resolved. As disccused, we will be moving the contracts to create a 721 collection for each project
